[package]
name = "fanrgb"
version = "0.1.0"
edition = "2021"
authors = ["itznan <https://github.com/itznan>"]
repository = "https://github.com/itznan/fanrgbmpgb550"

[dependencies]
hidapi = "2.6"
cpal = "0.15"
rustfft = "6.2"
libloading = "0.8"
ctrlc = "3.4"
num-complex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
